name: passenger-exporter Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Get dependencies
        run: go mod tidy

      - name: Check Syntax
        run: go vet ./...

  build:
    name: Build passenger-exporter Binary
    runs-on: ubuntu-latest
    needs: syntax-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build binary
        run: go build -v -o passenger-exporter ./...

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: passenger-exporter-linux-binary
          path: passenger-exporter
